### ISSUE TITLE
After users finish rating other images, they should be able to see their scores

### ISSUE THREAD

**Issue by chriswilmer** [alex-wilmer/rater#14]
When a user logs into a gallery:
- after the deadline has passed
- after they have finished rating other images

they should see the average rating their image received + their critical assessment score for that assignment, and also the qualitative feedback provided by the instructor

**Comment by alex-wilmer** [comment]
Will add instructor feedback along with https://github.com/alex-wilmer/rater/issues/13

https://github.com/alex-wilmer/rater/commit/84308e6ec05977ebca506f76e1cc24ad08a8b1bd
