### ISSUE TITLE
Change deadline? (or make it easy to delete a gallery)

### ISSUE THREAD

**Issue by chriswilmer** [alex-wilmer/rater#18]
I noticed that if I don't format the deadline date correctly, then the gallery is created with the current time as the deadline.

(Yeah, maybe some kind of calendar + clock would be helpful)

**Comment by alex-wilmer** [comment]
yup should be simple like adding the color picker component

**Comment by alex-wilmer** [comment]
same as this sort of. will edit issue

https://github.com/alex-wilmer/rater/issues/7
